import pandas as pd

df_q = pd.read_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions.tsv.train.tsv', sep='\t')
df_q_ = df_q[df_q['flags'].notna()].copy()
df_q__ = df_q_[df_q_['flags'].str.contains('SUCCESS')].copy()

print(len(df_q__))
df_q_shuffle=df_q__.sample(frac=1).reset_index(drop=True).copy()
print(len(df_q_shuffle))
df_q_shuffle.to_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions.tsv.train_shuffled.tsv', sep='\t')
df_dev_1=df_q_shuffle.iloc[0:int(len(df_q_shuffle)/5)].copy()
df_train_1 = df_q_shuffle.iloc[int(len(df_q_shuffle)/5):].copy()
df_dev_2=df_q_shuffle.iloc[int(len(df_q_shuffle)/5):2*int(len(df_q_shuffle)/5)].copy()
df_train_2 = pd.concat([df_dev_1, df_q_shuffle.iloc[2*int(len(df_q_shuffle)/5):].copy()])
df_dev_3 = df_q_shuffle.iloc[2*int(len(df_q_shuffle)/5):3*int(len(df_q_shuffle)/5)].copy()
df_train_3 = pd.concat([df_q_shuffle.iloc[0:2*int(len(df_q_shuffle)/5)].copy(), df_q_shuffle.iloc[3*int(len(df_q_shuffle)/5):].copy()])
df_dev_4 = df_q_shuffle.iloc[3*int(len(df_q_shuffle)/5):4*int(len(df_q_shuffle)/5)].copy()
df_train_4 = pd.concat([df_q_shuffle.iloc[0:3*int(len(df_q_shuffle)/5)].copy(), df_q_shuffle.iloc[4*int(len(df_q_shuffle)/5):].copy()])
df_dev_5 = df_q_shuffle.iloc[4*int(len(df_q_shuffle)/5):].copy()
df_train_5 = df_q_shuffle.iloc[0:4*int(len(df_q_shuffle)/5)].copy()
df_dev_1.to_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions_dev_1.tsv', sep='\t')
df_train_1.to_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions_train_1.tsv', sep='\t')
df_dev_2.to_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions_dev_2.tsv', sep='\t')
df_train_2.to_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions_train_2.tsv', sep='\t')
df_dev_3.to_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions_dev_3.tsv', sep='\t')
df_train_3.to_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions_train_3.tsv', sep='\t')
df_dev_4.to_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions_dev_4.tsv', sep='\t')
df_train_4.to_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions_train_4.tsv', sep='\t')
df_dev_5.to_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions_dev_5.tsv', sep='\t')
df_train_5.to_csv('/home/zeyuzhang/PycharmProjects/BERT_BERTPK_train_1/expl-tablestore-export-2019-09-10-165215/questions_train_5.tsv', sep='\t')
